DROP TABLE if EXISTS DOCENTES;
DROP TABLE if EXISTS CURSO_SUPERIOR;
DROP TABLE if EXISTS OUTROS_CURSOS;
DROP TABLE if EXISTS DEFICIENCIAS;
DROP TABLE if EXISTS ENDERECO;
DROP TABLE if EXISTS LOCAL_NASC;

CREATE TABLE DOCENTES(
    ID_DOCENTE INT NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    NU_IDADE_REFERENCIA INT NOT NULL,
    NU_IDADE INT NOT NULL,
    TP_SEXO INT NOT NULL,
    TP_COR_RACA INT,
    IN_NECESSIDADE_ESPECIAL BOOLEAN NOT NULL,
    TP_ESCOLARIDADE INT NOT NULL,
    TP_NORMAL_MAGISTERIO INT,
    IN_MESTRADO BOOLEAN,
    IN_DOUTORADO BOOLEAN,
    IN_POS_NENHUM BOOLEAN,
    IN_ESPECIALIZACAO BOOLEAN,
    TP_TIPO_DOCENTE INT NOT NULL,
    TP_TIPO_CONTRATACAO INT NOT NULL,
    
    CURSO_SUPERIOR INT NOT NULL,
    OUTROS_CURSOS INT NOT NULL,
    DEFICIENCIAS INT NOT NULL, 
    ENDERECO INT NOT NULL,
    LOCAL_NASC INT NOT NULL,
    
    CONSTRAINT FKEY_CURSO_SUPERIOR FOREIGN KEY (CURSO_SUPERIOR)
        REFERENCES CURSO_SUPERIOR(ID_CURSO_SUPERIOR),
    CONSTRAINT FKEY_OUTROS_CURSOS FOREIGN KEY (OUTROS_CURSOS)
        REFERENCES OUTROS_CURSOS(ID_OUTROS_CURSOS),
    CONSTRAINT FKEY_DEFICIENCIAS FOREIGN KEY (DEFICIENCIAS)
        REFERENCES DEFICIENCIAS(ID_DEFICIENCIAS),
    CONSTRAINT FKEY_ENDERECO FOREIGN KEY (ENDERECO)
        REFERENCES ENDERECO(ID_ENDERECO),
    CONSTRAINT FKEY_LOCAL_NASC FOREIGN KEY (LOCAL_NASC)
        REFERENCES LOCAL_NASC(ID_LOCAL_NASC),
);

CREATE TABLE CURSO_SUPERIOR(
    ID_CURSO_SUPERIOR INT NOT NULL UNIQUE,
    TP_SITUACAO_CURSO INT,
    IN_LICENCIATURA INT,
    IN_COM_PEDAGOGICA INT,
    NU_ANO_INICIO DATE NOT NULL,
    NU_ANO_CONCLUSAO DATE,
    TP_TIPO_IES INT,
    CO_IES INT NOT NULL,
    CO_AREA_CURSO INT NOT NULL,
    CO_CURSO INT NOT NULL,

    CONSTRAINT FKEY_CO_IES FOREIGN KEY (CO_IES)
        REFERENCES Anexo6_TabelaIES(CO_IES),
    CONSTRAINT FKEY_CO_AREA_CURSO FOREIGN KEY (CO_AREA_CURSO)
        REFERENCES Anexo6_TabelaIES(CO_AREA_CURSO),
    CONSTRAINT FKEY_CO_CURSO FOREIGN KEY (CO_CURSO)
        REFERENCES Anexo6_TabelaIES(CO_CURSO),

);

CREATE TABLE OUTROS_CURSOS(
    ID_OUTROS_CURSOS INT NOT NULL UNIQUE,
    IN_ESPECIFICO_CRECHE BOOLEAN NOT NULL,
    IN_ESPECIFICO_PRE_ESCOLA BOOLEAN NOT NULL,
    IN_ESPECIFICO_ANOS_INICIAIS BOOLEAN NOT NULL,
    IN_ESPECIFICO_ANOS_FINAIS BOOLEAN NOT NULL,
    IN_ESPECIFICO_ENS_MEDIO BOOLEAN NOT NULL,
    IN_ESPECIFICO_EJA BOOLEAN NOT NULL,
    IN_ESPECIFICO_ED_ESPECIAL BOOLEAN NOT NULL,
    IN_ESPECIFICO_ED_INDIGENA BOOLEAN NOT NULL,
    IN_ESPECIFICO_CAMPO BOOLEAN NOT NULL,
    IN_ESPECIFICO_AMBIENTAL BOOLEAN NOT NULL,
    IN_ESPECIFICO_DIR_HUMANOS BOOLEAN NOT NULL,
    IN_ESPECIFICO_DIV_SEXUAL BOOLEAN NOT NULL,
    IN_ESPECIFICO_DIR_ADOLESC BOOLEAN NOT NULL,
    IN_ESPECIFICO_AFRO BOOLEAN NOT NULL,
    IN_ESPECIFICO_OUTROS BOOLEAN NOT NULL,
    IN_ESPECIFICO_NENHUM BOOLEAN NOT NULL,

    PRIMARY KEY(ID_OUTROS_CURSOS)
);

CREATE TABLE DEFICIENCIAS(
    ID_DEFICIENCIAS INT NOT NULL UNIQUE,
    IN_CEGUEIRA BOOLEAN NOT NULL,
    IN_BAIXA_VISAO BOOLEAN NOT NULL,
    IN_SURDEZ BOOLEAN NOT NULL,
    IN_DEF_AUDITIVA BOOLEAN NOT NULL,
    IN_SURDOCEGUEIRA BOOLEAN NOT NULL,
    IN_DEF_FISICA BOOLEAN NOT NULL,
    IN_DEF_INTELECTUAL BOOLEAN NOT NULL,
    IN_DEF_MULTIPLA BOOLEAN NOT NULL,

    PRIMARY KEY(ID_DEFICIENCIAS)
);

CREATE TABLE ENDERECO(
    CO_UF_END INT NOT NULL,
    CO_MUNICIPIO_END INT NOT NULL,
    TP_ZONA_RESIDENCIAL INT NOT NULL,

    PRIMARY KEY(CO_UF_END, CO_MUNICIPIO_END, TP_ZONA_RESIDENCIAL)
);

CREATE TABLE LOCAL_NASC(
    CO_PAIS_ORIGEM INT NOT NULL,
    TP_NACIONALIDADE INT NOT NULL,
    CO_UF_NASC INT NOT NULL,
    CO_MUNICIPIO_NASC INT NOT NULL,

    PRIMARY KEY(CO_PAIS_ORIGEM, TP_NACIONALIDADE, CO_UF_NASC, CO_MUNICIPIO_NASC)
);