DROP TABLE if EXISTS DOCENTES;
DROP TABLE if EXISTS CURSO_SUPERIOR;
DROP TABLE if EXISTS OUTROS_CURSOS;
DROP TABLE if EXISTS DEFICIENCIAS;
DROP TABLE if EXISTS ENDERECO;
DROP TABLE if EXISTS LOCAL_NASC;

CREATE TABLE DOCENTES(
    ID_DOCENTE INT NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE,
    NU_IDADE_REFERENCIA INT,
    NU_IDADE INT,
    TP_SEXO INT,
    TP_COR_RACA INT,
    IN_NECESSIDADE_ESPECIAL BOOLEAN,
    TP_ESCOLARIDADE INT,
    TP_NORMAL_MAGISTERIO INT,
    IN_MESTRADO BOOLEAN,
    IN_DOUTORADO BOOLEAN,
    IN_POS_NENHUM BOOLEAN,
    IN_ESPECIALIZACAO BOOLEAN,
    TP_TIPO_DOCENTE INT,
    TP_TIPO_CONTRATACAO INT,
    
    OUTROS_CURSOS INT REFERENCES OUTROS_CURSOS(ID_OUTROS_CURSOS)
);

CREATE TABLE CURSO_SUPERIOR(
    
    TP_SITUACAO_CURSO INT,
    IN_LICENCIATURA INT,
    IN_COM_PEDAGOGICA INT,
    NU_ANO_INICIO DATE,
    NU_ANO_CONCLUSAO DATE,
    TP_TIPO_IES INT,
    CO_IES INT REFERENCES Anexo6_TabelaIES(CO_IES),
    CO_AREA_CURSO INT REFERENCES Anexo5_CursosFormaçãoSuperior(CO_AREA_CURSO),
    CO_CURSO INT REFERENCES Anexo5_CursosFormaçãoSuperior(CO_CURSO),
);

CREATE TABLE OUTROS_CURSOS(
    ID_OUTROS_CURSOS INT NOT NULL UNIQUE,
    IN_ESPECIFICO_CRECHE BOOLEAN,
    IN_ESPECIFICO_PRE_ESCOLA BOOLEAN,
    IN_ESPECIFICO_ANOS_INICIAIS BOOLEAN,
    IN_ESPECIFICO_ANOS_FINAIS BOOLEAN,
    IN_ESPECIFICO_ENS_MEDIO BOOLEAN,
    IN_ESPECIFICO_EJA BOOLEAN,
    IN_ESPECIFICO_ED_ESPECIAL BOOLEAN,
    IN_ESPECIFICO_ED_INDIGENA BOOLEAN,
    IN_ESPECIFICO_CAMPO BOOLEAN,
    IN_ESPECIFICO_AMBIENTAL BOOLEAN,
    IN_ESPECIFICO_DIR_HUMANOS BOOLEAN,
    IN_ESPECIFICO_DIV_SEXUAL BOOLEAN,
    IN_ESPECIFICO_DIR_ADOLESC BOOLEAN,
    IN_ESPECIFICO_AFRO BOOLEAN,
    IN_ESPECIFICO_OUTROS BOOLEAN,
    IN_ESPECIFICO_NENHUM BOOLEAN
);

CREATE TABLE DEFICIENCIAS(
    ID_DEFICIENCIAS INT NOT NULL UNIQUE,
    IN_CEGUEIRA BOOLEAN,
    IN_BAIXA_VISAO BOOLEAN,
    IN_SURDEZ BOOLEAN,
    IN_DEF_AUDITIVA BOOLEAN,
    IN_SURDOCEGUEIRA BOOLEAN,
    IN_DEF_FISICA BOOLEAN,
    IN_DEF_INTELECTUAL BOOLEAN,
    IN_DEF_MULTIPLA BOOLEAN
    
);

CREATE TABLE ENDERECO(
    CO_UF_END INT,
    CO_MUNICIPIO_END INT,
    TP_ZONA_RESIDENCIAL INT
);

CREATE TABLE LOCAL_NASC(
    CO_PAIS_ORIGEM INT,
    TP_NACIONALIDADE INT,
    CO_UF_NASC INT,
    CO_MUNICIPIO_NASC INT
);