insert into in_mantenedor (in_mantenedor) values
('IN_MAT_ESCOLA_PRIVADA_EMP'),
('IN_MAT_ESCOLA_PRIVADA_ONG'),
('IN_MAT_ESCOLA_PRIVADA_SIND'),
('IN_MAT_ESCOLA_PRIVADA_SIST_S'),
('IN_MAT_ESCOLA_PRIVADA_S_FINS');

insert into in_local_funcionamento(in_local_funcionamento) VALUES
('IN_LOCAL_FUNC_PREDIO_ESCOLAR'),
('IN_LOCAL_FUNC_SALAS_EMPRESA'),
('IN_LOCAL_FUNC_SOCIOEDUCATIVO'),
('IN_LOCAL_FUNC_UNID_PRISIONAL'),
('IN_LOCAL_FUNC_PRISIONAL_SOCIO'),
('IN_LOCAL_FUNC_TEMPLO_IGREJA'),
('IN_LOCAL_FUNC_CASA_PROFESSOR'),
('IN_LOCAL_FUNC_GALPAO'),
('IN_LOCAL_FUN_SALAS_OUTRA_ESC'),
('IN_LOCAL_FUN_SALAS_OUTROS'),
('IN_PREDIO_COMPARTILHADO');

insert into in_agua(in_agua) VALUES
('IN_AGUA_FILTRADA'),
('IN_AGUA_REDE_PUBLICA'),
('IN_AGUA_POCO_ARTESIANO'),
('IN_AGUA_CACIMBA'),
('IN_AGUA_FONTE_RIO'),
('IN_AGUA_INEXISTENTE');

insert into in_energia(in_energia) VALUES
('IN_ENERGIA_REDE_PUBLICA'),
('IN_ENERGIA_GERADOR'),
('IN_ENERGIA_OUTROS'),
('IN_ENERGIA_INEXISTENTE');

insert into in_esgoto(in_esgoto) VALUES
('IN_ESGOTO_REDE_PUBLICA'),
('IN_ESGOTO_FOSSA'),
('IN_ESGOTO_INEXISTENTE');

insert into in_lixo(in_lixo) VALUES
('IN_LIXO_COLETA_PERIODICA'),
('IN_LIXO_QUEIMA'),
('IN_LIXO_JOGA_OUTRA_AREA'),
('IN_LIXO_RECICLA'),
('IN_LIXO_ENTERRA'),
('IN_LIXO_OUTROS');

insert into in_dependencias(in_dependencias) VALUES
('IN_SALA_DIRETORIA'),
('IN_SALA_PROFESSOR'),
('IN_SALA_ATENDIMENTO_ESPECIAL'),
('IN_SALA_LEITURA'),
('IN_LABORATORIO_INFORMATICA'),
('IN_LABORATORIO_CIENCIAS'),
('IN_QUADRA_ESPORTES_COBERTA'),
('IN_QUADRA_ESPORTES_DESCOBERTA'),
('IN_QUADRA_ESPORTES'),
('IN_COZINHA'),
('IN_BIBLIOTECA'),
('IN_BIBLIOTECA_SALA_LEITURA'),
('IN_PARQUE_INFANTIL'),
('IN_BERCARIO'),
('IN_BANHEIRO_FORA_PREDIO'),
('IN_BANHEIRO_DENTRO_PREDIO'),
('IN_BANHEIRO_EI'),
('IN_BANHEIRO_PNE'),
('IN_DEPENDENCIAS_PNE'),
('IN_SECRETARIA'),
('IN_BANHEIRA_CHUVEIRO'),
('IN_REFEITORIO'),
('IN_DESPANSA'),
('IN_ALMOXARIFADO'),
('IN_AUDITORIO'),
('IN_PATIO_COBERTO'),
('IN_PATIO_DESCOBERTO'),
('IN_ALOJAM_ALUNO'),
('IN_ALOJAM_PROFESSOR'),
('IN_AREA_VERDE'),
('IN_LAVANDERIA'),
('IN_DEPENDENCIAS_OUTRAS');


insert into in_equipamentos(in_equipamentos) VALUES
('IN_EQUIP_TV'),
('IN_EQUIP_VIDEOCASSETE'),
('IN_EQUIP_DVD'),
('IN_EQUIP_PARABOLICA'),
('IN_EQUIP_COPIADORA'),
('IN_EQUIP_RETROPROJETOR'),
('IN_EQUIP_IMPRESSORA'),
('IN_EQUIP_IMPRESSORA_MULT'),
('IN_EQUIP_SOM'),
('IN_EQUIP_MULTIMIDIA'),
('IN_EQUIP_FAX'),
('IN_EQUIP_FOTO'),
('IN_COMPUTADOR');

insert into in_internet(in_internet) VALUES
('IN_INTERNET'),
('IN_BANDA_LARGA');

insert into in_alimentacao(in_alimentacao) VALUES
('IN_ALIMENTACAO');

insert into in_educacao_indigena(in_educacao_indigena) VALUES
('IN_EDUCACAO_INDIGENA');

insert into in_brasil_alfabetizado(in_brasil_alfabetizado) VALUES
('IN_BRASIL_ALFABETIZADO');

insert into in_final_semana(in_final_semana) VALUES
('IN_FINAL_SEMANA');

insert into in_formacao_alternancia(in_formacao_alternancia) VALUES
('IN_FORMACAO_ALTERNANCIA');

insert into in_conveniada_pp(in_conveniada_pp) VALUES
('IN_CONVENIADA_PP');

insert into in_fundamental_ciclos(in_fundamental_ciclos) VALUES
('IN_FUNDAMENTAL_CICLOS');

insert into in_material(in_material) VALUES
('IN_MATERIAL_ESP_QUILOMBOLA'),
('IN_MATERIAL_ESP_INDIGENA'),
('IN_MATERIAL_ESP_NAO_UTILIZA');

